wandb_version: 1

M:
  desc: null
  value: 640
N:
  desc: null
  value: 192
_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1730106462
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 16
      4: 3.7.11
      5: 0.12.10
      8:
      - 5
all_scalable:
  desc: null
  value: false
aux_learning_rate:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 16
checkpoint:
  desc: null
  value: none
checkpoint_base:
  desc: null
  value: none
checkpoint_enh:
  desc: null
  value: none
clip_max_norm:
  desc: null
  value: 1.0
code:
  desc: null
  value: mdmh-mem5-de
continue_training:
  desc: null
  value: false
cuda:
  desc: null
  value: false
delta_encode:
  desc: null
  value: true
dim_chunk:
  desc: null
  value: 32
division_dimension:
  desc: null
  value:
  - 320
  - 640
double_dim:
  desc: null
  value: false
epochs:
  desc: null
  value: 150
freeze:
  desc: null
  value: false
freeze_base:
  desc: null
  value: false
inner_dimensions:
  desc: null
  value:
  - 192
  - 192
joiner_policy:
  desc: null
  value: res
learning_rate:
  desc: null
  value: 0.0001
list_quality:
  desc: null
  value:
  - 0
lmbda_list:
  desc: null
  value:
  - 0.0055
  - 0.04
mask_policy:
  desc: null
  value: two-levels
milestones:
  desc: null
  value:
  - 0
  - 0.75
  - 1.5
  - 3
  - 10
model:
  desc: null
  value: channel
multiple_decoder:
  desc: null
  value: true
multiple_encoder:
  desc: null
  value: false
multiple_hyperprior:
  desc: null
  value: true
name_model:
  desc: null
  value: none
num_images:
  desc: null
  value: 1200
num_images_val:
  desc: null
  value: 816
num_workers:
  desc: null
  value: 8
patch_size:
  desc: null
  value:
  - 256
  - 256
patience:
  desc: null
  value: 8
residual_before_lrp:
  desc: null
  value: false
sampling_training:
  desc: null
  value: false
save:
  desc: null
  value: true
seed:
  desc: null
  value: 42.0
support_progressive_slices:
  desc: null
  value: 5
support_std:
  desc: null
  value: false
test_batch_size:
  desc: null
  value: 1
tester:
  desc: null
  value: false
total_mu_rep:
  desc: null
  value: false
u_net_post:
  desc: null
  value: 0
valid_batch_size:
  desc: null
  value: 16
